# Branch protection rules for main branch
protection:
  # Require pull request reviews before merging
  required_pull_request_reviews:
    required_approving_review_count: 1
    dismiss_stale_reviews: true
    require_code_owner_reviews: true
    require_last_push_approval: true

  # Require status checks to pass before merging
  required_status_checks:
    strict: true
    contexts:
      - lint
      - test
      - deploy
      - healthcheck

  # Include administrators in restrictions
  enforce_admins: true

  # Restrict who can push to the protected branch
  restrictions:
    apps: []
    users: []
    teams: []

  # Require linear history
  required_linear_history: true

  # Allow force pushes
  allow_force_pushes: false

  # Allow deletions
  allow_deletions: false