[build]
command = "next build"
publish = ".next"

[functions]
directory = "netlify/functions"

[[plugins]]
package = "@netlify/plugin-nextjs"

[build.environment]
NEXT_PRIVATE_STANDALONE = "true"

[context.production.environment]
NODE_VERSION = "20"

[headers]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"